# POST https://<BIG-IP>/mgmt/shared/declarative-onboarding
# GET https://<BIG-IP>/mgmt/shared/declarative-onboarding?show=full

# auth token
# POST /mgmt/shared/authn/login
# Host: {{bigip_host}}
# Authorization: Basic {Base64encoded value of username:password}
# Content-Type: application/json
# {
#     "username":"{userWithCorrectPerms}",
#     "password":"{userPassword}",
#     "loginProviderName":"tmos"
# }
# token timeout
# PATCH /mgmt/shared/authz/tokens/{{bigip_auth_token}}
# Host: {{bigip_host}}
# Content-Type: application/json
# X-F5-Auth-Token: {{bigip_auth_token}}
# {
#     "timeout":"36000" //this is the maximum
# }
# post examples
#
# - uri:
#     url: https://your.form.based.auth.example.com/index.php
#     method: POST
#     body_format: form-urlencoded
#     body:
#       name: your_username
#       password: your_password
#       enter: Sign in
#     status_code: 302
#   register: login
# - name: Create a JIRA issue
# uri:
#   url: https://your.jira.example.com/rest/api/2/issue/
#   method: POST
#   user: your_username
#   password: your_pass
#   body: "{{ lookup('file','issue.json') }}"
#   force_basic_auth: yes
#   status_code: 201
#   body_format: json

# - name: get auth token
#   uri:
#     url: "https://{{ provider.server }}{{ authUrl }}"
#     method: POST
#     body_format: json
#     user: "{{ provider.user }}"
#     password: "{{ provider.password }}"
#     return_content: true
#     validate_certs: false
#     body: {"username":"{{ provider.user }}","password":"{{ provider.password }}","loginProviderName":"tmos"}
#     status_code: 200
#   register: token
#   delegate_to: localhost
# - debug:
#     msg: "{{ token }}"
# - debug:
#     msg: "{{ token.json.token.token }}"
# - name: check for DO
#   uri: 
#     url: "https://{{ provider.server }}{{ doUrl }}?show=full"
#     method: GET
#     headers:
#       X-F5-Auth-Token: "{{ token.json.token.token }}"
#     return_content: true
#     validate_certs: false
#     status_code: 200
#   register: doStatus
#   delegate_to: localhost
#   when: token.json.token.token != ""
# - debug:
#     msg: "{{ doStatus }}"
- name: POST DO
  uri:
    url: "https://{{ provider.server }}{{ doUrl }}"
    method: POST
    headers:
      X-F5-Auth-Token: "{{ token.json.token.token }}"
    return_content: true
    validate_certs: false
    body_format: json
    body: "{{ lookup('file', doFilePath, errors='strict' ) }}"
    status_code: 202, 200
  register: doResult
  delegate_to: localhost
# - debug:
#     msg: "{{ doResult }}"
  #when: doStatus.json is search("/declaration/")
  #body: "{{ lookup('file','myvalues.json') }}"
  #"{{ hostvars[inventory_hostname]['provider'] }}"

  #     provider: "{{ hostvars[inventory_hostname]['provider'] }}"
  # rpmPath: "{{ inventory_dir }}/host_vars/{{ hostvars[inventory_hostname] }}/do.json"
  # doPath: "{{ inventory_dir }}/host_vars/{{ hostvars[inventory_hostname] }}/do.json"